### ISSUE TITLE
生成导航

### ISSUE THREAD

**Issue by creamidea** [creamidea/creamidea.github.com#3]
__config.yml_

``` yaml
bucket_title:
- text: archive
  url: /archive/index.html
- text: tags
  url: /tags/index.html
- text: draft
  url: https://github.com/creamidea/creamidea.github.com/tree/master/_draft
- text: emotion
  url: http://www.douban.com/people/creamidea/notes
```

_bucket_title.html_

``` html
{% unless page.layout == 'front' %}
<nav class="bucket-sort">
  {% for title in site.bucket_title %}
  {% assign page_url = page.url|split: '/' %}
  {% if page_url[1] == title.text or page.layout == link.layout %}
  {% assign href = "#" %}
  {% assign class = "no-link" %}
  {% assign active = "active" %}
  {% else %}
  {% assign href = title.url %}
  {% assign class = "" %}
  {% assign active = "" %}
  {% endif %}
  <h5 class="bucket-title {{active}}">
    <a  href="{{ href }}" class="{{ class }}">
      <span class="bucket-header-title">{{ title.text }}</span>
    </a>
  </h5>
  {% endfor %}
</nav>
{% endunless %}
```
